### ISSUE TITLE
Handling singleton dimension in h5 DS

### ISSUE THREAD

**Issue by sommerc** [rosalindfranklininstitute/napari-h5#1]
Hi there!

this plugin is excactly what I was looking for, thank you!

One little question:

My .h5 may datasets contain **singleton dimensions**, and I would like the reader to ignore them:

Would it be possible to "**squeeze()**" them out in line

https://github.com/rosalindfranklininstitute/napari-h5/blob/a5050487cb854e889ed8bcfaf25315dfe4b3faaa/src/napari_h5/_reader.py#L98

If you prefer I could do a PR.

Cheers,
Chris

**Comment by perdigao1** [comment]
Hi. Can you precisely describe what a singleton dimension is?

Does it mean that one of the dimensions has a length of one? , like data.shape =(1,256,256) ?

**Comment by sommerc** [comment]
Yes excactly. I have images, which for instance contain time, z-slices, channels, Y and X: 

"TZYXC" with a shape [100, 10, 256, 256, 1]

Napari + napari-h5 will then display not 2D, but a single column (at least when the singleton is at the end) ...

**Comment by perdigao1** [comment]
I can probably add something that automatically detects the singleton dimensions, also applying to things like [1,100,10,256,256], but then.... maybe users want to preserve that.... or pull up a dialog prompting user to choose whether to squeeze or not.

Or perhaps, it would be better for the source of data to do the squeezing before saving....

**Comment by sommerc** [comment]
I think both use cases are possible. Perhaps the h5-reader could have a global setting how to deal with singleton dims, or an per file/dataset user dialog to dicide how to proceed when they occur.

In my case the data comes from the FIJI ilastik-exporter. They have the convention to always export 5D datasets...

**Comment by sommerc** [comment]
related discussion :-)

https://github.com/napari/napari/issues/3469

**Comment by perdigao1** [comment]
Should be resolved in latest, version 0.8
